language: php

php:
  - 7.0

before_script:
  - travis_retry composer self-update --no-progress -n
  - travis_retry composer install -n --prefer-dist

script:
  # Find php syntax errors
  - php -l app
  - php -l tests

  # Run unit tests
  - phpunit --coverage-text

  # Check for coding standard violations
  - vendor/bin/phpcs --standard=PSR2 app tests

notifications:
  email:
    on_success: never