# This is production configuration for the app
# Environment variables that are listed, but are missing a value MUST be given from the environment
# (example: `$ MYSQL_PASSWORD=pass MYSQL_ROOT_PASSWORD=pass docker-compose up`)
app:
  image: anroots/dag
  ports:
    - 80
  links:
    - db
  environment:
    APP_ENV: production
    APP_DEBUG: 'false'
    # Random, secret key
    APP_KEY:
db:
  image: mariadb
  environment:
    # Database passwords
    MYSQL_ROOT_PASSWORD:
    MYSQL_PASSWORD:

    MYSQL_USER: app
    MYSQL_DATABASE: app
  ports:
    - 3306